### ISSUE TITLE
Running oandatb.py failes 

### ISSUE THREAD

**Issue by ramy-osama84** [yhilpisch/aiif#3]
Hello,
 I'm facing an issue when i'm running oandatb.py because the below error although i saw that inside tradingbot.py eager mode is disabled i'm using the same version TF 2.3:
Traceback (most recent call last):
  File "oandatb.py", line 118, in <module>
    otb.stream_data(agent.learn_env.symbol)
  File "/home/ramy/aiif-main/code/aiif/lib/python3.8/site-packages/tpqoa/tpqoa.py", line 285, in stream_data
    self.on_success(msg.time,
  File "oandatb.py", line 90, in on_success
    prediction = np.argmax(self.agent.model.predict(state)[0, 0])
  File "/home/ramy/aiif-main/code/aiif/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1577, in predict
    version_utils.disallow_legacy_graph('Model', 'predict')
  File "/home/ramy/aiif-main/code/aiif/lib/python3.8/site-packages/tensorflow/python/keras/utils/version_utils.py", line 122, in disallow_legacy_graph
    raise ValueError(error_msg)
ValueError: Calling `Model.predict` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.predict` with eager mode enabled.

**Comment by yhilpisch** [comment]
Did you try to comment out the `disable_eager_execution()` line of code?

**Comment by ramy-osama84** [comment]
Yes it's working now but constructing the model is taking much longer.

**Comment by yhilpisch** [comment]
That is the reason why eager execution is disabled here.

Your error might have something to do with the placement of the `disable_eager_execution()` call (sequence of execution).

Unfortunately, the behaviour of TF/Keras has changed to some extent across versions in this regard.
